[info]

name = "Goputer Python"
description = "Graphical frontend implemented in Python"
authour = "Oscar Peace (sccreeper)"
repository = "https://github.com/sccreeper/goputer"
run = ["./goputerpy", "-e", "$executable", "-p", "$use_profiler", "-o", "$profiler_out"]

[build]

command = ["sh", "cmd.sh"]
output_dir = "build"
artifact = "frontend.goputerpy"