// Code generated by command: go run video_area_alpha.go -out video_area_alpha_amd64.s -stubs video_area_alpha_amd64.go. DO NOT EDIT.

package asm

func VideoAreaAlphaAsm(array *byte, red uint8, green uint8, blue uint8, alpha uint8, x uint32, y uint32, x1 uint32, y1 uint32)
