// Code generated by command: go run video_clear.go -out video_clear_amd64.s -stubs video_clear_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func VideoClearAsm(array *byte, red uint8, green uint8, blue uint8)
TEXT ·VideoClearAsm(SB), NOSPLIT, $0-11
	MOVQ array+0(FP), AX
	MOVB red+8(FP), CL
	MOVB green+9(FP), DL
	MOVB blue+10(FP), BL
	MOVQ AX, SI
	ADDQ $0x00038400, SI

loop:
	MOVB CL, (AX)
	INCQ AX
	MOVB DL, (AX)
	INCQ AX
	MOVB BL, (AX)
	INCQ AX
	CMPQ AX, SI
	JBE  loop
	RET
