// Code generated by command: go run video_area_alpha.go -out video_area_alpha_amd64.s -stubs video_area_alpha_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func VideoAreaAlphaAsm(array *byte, red uint8, green uint8, blue uint8, alpha uint8, x uint32, y uint32, x1 uint32, y1 uint32)
// Requires: AVX, AVX2, SSE2
TEXT ·VideoAreaAlphaAsm(SB), NOSPLIT, $0-28
	// Load parameters
	MOVQ array+0(FP), AX
	MOVB red+8(FP), CL
	MOVB green+9(FP), DL
	MOVB blue+10(FP), BL
	MOVB alpha+11(FP), DI
	MOVL x+12(FP), SI
	MOVL y+16(FP), R9
	MOVL x1+20(FP), R10
	MOVL y1+24(FP), R11
	XORB R12, R12

	// Offset pointer by x and y
	MOVL  R9, R12
	MOVQ  $0x00000000000003c0, R13
	IMULQ R13, R12
	ADDQ  R12, AX
	MOVL  SI, R12
	MOVQ  $0x0000000000000003, R13
	IMULQ R13, R12
	ADDQ  R12, AX

	// Bounds
	SUBL R9, R11
	SUBL SI, R10

	// Fill alpha register
	MOVBLZX      DI, R12
	MOVD         R12, X3
	VPBROADCASTB X3, X3
	VPMOVZXBW    X3, Y0
	VPXOR        X3, X3, X3
	MOVB         DI, R8
	NOTB         R8
	MOVBWZX      R8, SI
	MOVBLZX      R8, R12
	MOVD         R12, X3
	VPBROADCASTB X3, X3
	VPMOVZXBW    X3, Y1

	// Construct colour
	MOVB      BL, R8
	SHLL      $0x08, R8
	MOVB      DL, R8
	SHLL      $0x08, R8
	MOVB      CL, R8
	VPXOR     X3, X3, X3
	MOVD      R8, X3
	VPSHUFB   shuffle_mask<>+0(SB), X3, X3
	VPMOVZXBW X3, Y2
	VPMULLW   Y2, Y0, Y2
	XORL      R8, R8
	XORL      R9, R9

	// Construct colour for remaining
	MOVBWZX CL, CX
	MOVBWZX DL, DX
	MOVBWZX BL, BX
	MOVBWZX DI, DI
	IMULW   DI, CX
	IMULW   DI, DX
	IMULW   DI, BX

	// Loop to fill for alpha
a_loop:
	MOVQ AX, DI
	CMPL R10, $0x05
	JB   a_blit_remaining

a_loop_x:
	// Check if less than 5 pixels to blit
	MOVL R8, R12
	ADDL $0x05, R12
	CMPL R12, R10
	JA   a_blit_remaining

	// Otherwise blit 5 pixels at a time
	// Load data to be modified from memory
	VMOVDQU (DI), X3
	MOVB    15(DI), R12

	// Modify memory data
	VPMOVZXBW    X3, Y0
	VPMULLW      Y0, Y1, Y0
	VPADDW       Y0, Y2, Y0
	VPSRLW       $0x08, Y0, Y0
	VPACKUSWB    Y0, Y0, Y0
	VPERMQ       $0xd8, Y0, Y0
	VEXTRACTI128 $0x00, Y0, X3

	// Move data back to memory
	VMOVDQU X3, (DI)
	MOVB    R12, 15(DI)
	ADDQ    $0x0f, DI
	ADDL    $0x05, R8
	CMPL    R8, R10
	JBE     a_loop_x
	JA      a_loop_end

a_blit_remaining:
	MOVBWZX (DI), R12
	IMULW   SI, R12
	ADDW    CX, R12
	SHRW    $0x08, R12
	MOVB    R12, (DI)
	MOVBWZX 1(DI), R12
	IMULW   SI, R12
	ADDW    DX, R12
	SHRW    $0x08, R12
	MOVB    R12, 1(DI)
	MOVBWZX 2(DI), R12
	IMULW   SI, R12
	ADDW    BX, R12
	SHRW    $0x08, R12
	MOVB    R12, 2(DI)
	ADDQ    $0x03, DI
	INCL    R8
	CMPL    R8, R10
	JB      a_blit_remaining

	// Cleanup
a_loop_end:
	XORL R8, R8
	ADDQ $0x000003c0, AX
	INCL R9
	CMPL R9, R11
	JB   a_loop
	RET

DATA shuffle_mask<>+0(SB)/16, $"\x00\x01\x02\x00\x01\x02\x00\x01\x02\x00\x01\x02\x00\x01\x02\x00"
GLOBL shuffle_mask<>(SB), RODATA|NOPTR, $16
