// Code generated by command: go run video_clear.go -out video_clear_amd64.s -stubs video_clear_amd64.go. DO NOT EDIT.

package asm

func VideoClearAsm(array *byte, red uint8, green uint8, blue uint8)
