[info]

# Authour info

name = "Goputer System Module"
description = "The system module for goputer"
authour = "Oscar Peace (sccreeper)"
repository = "https://github.com/sccreeper/goputer"

# ID of the module, used when querying modules. This is also the name of the entrypoint, e.g. goputer.sys.so or goputer.sys.lua
id = "goputer.sys"

# Attributes that can be set & retrieved by the frontend
attributes = ["name", "display_width", "display_height", "memory", "expansions"]

[build]

command = ["sh", "build.sh"]
output_dir = "build"
artifact = "expansion.goputer.sys"