[info]

name = "GP32"
description = "Default graphical frontend"
authour = "Oscar Peace (sccreeper)"
repository = "https://github.com/sccreeper/goputer"
run = ["./gp32", "-e", "$executable", "$use_profiler:--useprofiler", "$profiler_out:--profilerout", "$profiler_out"]

[build]

command = ["sh", "cmd.sh"]
output_dir = "build"
artifact = "frontend.gp32"