[info]

name = "GP32"
description = "Default graphical frontend"
authour = "Oscar Peace (sccreeper)"
repository = "https://github.com/sccreeper/goputer"
is_plugin = true

[build]

command = ["sh", "cmd.sh"]
output_dir = "build"
artifact = "frontend.gp32"