[info]

name = "Goputer WASM"
description = "Graphical frontend implemented in JavaScript using WASM."
authour = "Oscar Peace (sccreeper)"
repository = "https://github.com/sccreeper/goputer"
run = []

[build]

command = ["sh", "cmd.sh"]
output_dir = "build"
artifact = "frontend.web"